name: magma-access-gateway
base: core20
version: '1.9'
summary: Magma's core network
description: Magma's core network

grade: devel
confinement: devmode

package-repositories:
  - type: apt
    components:
      - jdk1.8
    suites:
      - stable
    url: https://storage.googleapis.com/bazel-apt
    key-id: 71A1D0EFCFEB6281FD0437C93D5919B448457EE0
    key-server: https://bazel.build/bazel-release.pub.gpg

parts:

  bcc-tools:
    plugin: cmake
    source: https://github.com/iovisor/bcc.git
    source-type: git
    source-branch: v0.23.0
    cmake-parameters:
      - -DPYTHON_CMD=python3
    build-packages:
      - bison
      - flex
      - libedit-dev
      - libllvm7
      - llvm-7-dev
      - libclang-7-dev
      - python3
      - zlib1g-dev
      - libelf-dev
      - libfl-dev
      - luajit
      - libluajit-5.1-dev

  liblfds:
    plugin: make
    source: https://liblfds.org/git/liblfds
    source-type: git
    override-build: |
      set -x
      cd liblfds/liblfds7.1.0/liblfds710/build/gcc_gnumake
      make so_vanilla
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/local/include $SNAPCRAFT_PART_INSTALL/usr/local/lib
      make INSINCDIR="$SNAPCRAFT_PART_INSTALL/usr/local/include" INSLIBDIR="$SNAPCRAFT_PART_INSTALL/usr/local/lib" so_install

  oai-asn1c:
    plugin: autotools
    source: https://gitlab.eurecom.fr/oai/asn1c.git
    source-type: git
    source-commit: f12568d617dbf48497588f8e227d70388fa217c9

  oai-gnutls:
    plugin: autotools
    after:
      - oai-nettle
    source: http://mirrors.dotsrc.org/gcrypt/gnutls/v3.1/gnutls-3.1.23.tar.xz
    source-type: tar
    autotools-configure-parameters:
      - --with-libnettle-prefix=/root/parts/oai-nettle/install/usr/local/
    build-packages:
      - libtasn1-6-dev
      - libp11-kit-dev
      - libtspi-dev
      - libidn2-0-dev
      - libidn11-dev
    stage-packages:
      - libidn11
      - libtspi1
    override-build: |
      set -x
      patch gl/stdio-impl.h <<'EOF'
      @@ -18,6 +18,9 @@
          the same implementation of stdio extension API, except that some fields
          have different naming conventions, or their access requires some casts.  */

      +#if !defined _IO_IN_BACKUP && defined _IO_EOF_SEEN
      +# define _IO_IN_BACKUP 0x100
      +#endif

       /* BSD stdio derived implementations.  */

      EOF
      patch gl/fseterr.c <<'EOF'
      @@ -29,7 +29,7 @@
         /* Most systems provide FILE as a struct and the necessary bitmask in
            <stdio.h>, because they need it for implementing getc() and putc() as
            fast macros.  */
      -#if defined _IO_ftrylockfile || __GNU_LIBRARY__ == 1 /* GNU libc, BeOS, Haiku, Linux libc5 */
      +#if defined _IO_EOF_SEEN || __GNU_LIBRARY__ == 1 /* GNU libc, BeOS, Haiku, Linux libc5 */
         fp->_flags |= _IO_ERR_SEEN;
       #elif defined __sferror || defined __DragonFly__ /* FreeBSD, NetBSD, OpenBSD, DragonFly, Mac OS X, Cygwin */
         fp_->_flags |= __SERR;
      EOF
      snapcraftctl build

  oai-freediameter:
    plugin: cmake
    after:
      - oai-gnutls
    source: .
    cmake-parameters:
      - -DCMAKE_C_FLAGS=-DOLD_SCTP_SOCKET_API=1
    stage-packages:
      - libidn11
      - libsctp1
      - libtspi1
    override-build: |
      set -x
      cd $SNAPCRAFT_PART_SRC
      rm -rf opencord.org.freeDiameter
      git clone https://github.com/lionelgo/opencord.org.freeDiameter.git
      cd opencord.org.freeDiameter
      git checkout 13b0e7de0d66906d50e074a339f890d6e59813ad
      patch -p1 < "$SNAPCRAFT_PART_SRC/patches/oai-freediameter/0001-opencoord.org.freeDiameter.patch"
      patch -p1 < "$SNAPCRAFT_PART_SRC/patches/oai-freediameter/0002-opencoord.org.freeDiameter.patch"
      awk '{if (/^DISABLE_SCTP/) gsub(/OFF/, "ON"); print}' CMakeCache.txt > tmp && mv tmp CMakeCache.txt
      cp -rf $SNAPCRAFT_PART_SRC/opencord.org.freeDiameter/* $SNAPCRAFT_PART_SRC/

      cp -rf -L /root/parts/oai-gnutls/install/usr/local/lib/* /usr/local/lib/
      cp -rf -L /root/parts/oai-gnutls/install/usr/local/include/* /usr/local/include/

      snapcraftctl build

  oai-nettle:
    plugin: autotools
    source: https://ftp.gnu.org/gnu/nettle/nettle-2.5.tar.gz
    source-type: tar
    build-packages:
      - libgmp-dev
    autotools-configure-parameters:
      - --disable-openssl
      - --enable-shared

  fmt:
    plugin: cmake
    source: https://github.com/fmtlib/fmt.git
    source-type: git
    source-tag: 9.1.0
    cmake-parameters:
      - -DBUILD_SHARED_LIBS=ON
      - -DFMT_TEST=0

  folly:
    plugin: cmake
    after:
      - fmt
    source: https://github.com/facebook/folly
    source-type: git
    source-tag: v2021.02.15.00
    cmake-parameters:
      - -DBUILD_SHARED_LIBS=on
    build-packages:
      - libgoogle-glog-dev
      - libgflags-dev
      - libboost-all-dev
      - libevent-dev
      - libdouble-conversion-dev
      - libboost-chrono-dev
      - libiberty-dev
      - libssl-dev
    stage-packages:
      - libboost-context1.71.0
      - libboost-filesystem1.71.0
      - libboost-program-options1.71.0
      - libboost-regex1.71.0
      - libdouble-conversion3
      - libevent-2.1-7
      - libgflags2.2
      - libgoogle-glog0v5
      - libicu66
      - libsodium23
      - libunwind8
    override-build: |
      set -x
      cp -r /root/parts/fmt/install/usr/local/include/* /usr/local/include/
      cp -r /root/parts/fmt/install/usr/local/lib/* /usr/local/lib/
      snapcraftctl build

  magma-access-gateway:
    plugin: nil
    after:
      - folly
      - bcc-tools
      - oai-asn1c
      - oai-freediameter
      - oai-gnutls
      - oai-nettle
    source: https://github.com/magma/magma
    source-type: git
    build-packages:
      - apt-transport-https
      - apt-utils
      - bazel=5.2.0
      - bison
      - build-essential
      - ca-certificates
      - cmake
      - curl
      - gcc
      - gnupg2
      - g++
      - iproute2
      - iputils-ping
      - flex
      - libconfig-dev
      - libcurl4-openssl-dev
      - libczmq-dev
      - libgcrypt-dev
      - libgmp3-dev
      - libidn11-dev
      - libmnl-dev=1.0.4-2
      - libpcap-dev=1.9.1-3
      - libsctp1
      - libsqlite3-dev
      - libsctp-dev
      - libssl-dev
      - libsystemd-dev
      - lld
      - net-tools
      - netbase
      - python3.8
      - python-is-python3
      - python3-distutils
      - systemd
      - uuid-dev
      - vim
      - libtool=2.4.6-14
    override-build: |
      set -x
      
      cp -r -L /root/parts/folly/install/usr/local/include/* /usr/local/include/
      cp -r -L /root/parts/folly/install/usr/local/lib/* /usr/local/lib/
      
      cp -r -L /root/parts/oai-gnutls/install/usr/local/include/* /usr/include/
      cp -r -L /root/parts/oai-gnutls/install/usr/local/lib/* /usr/lib/
      cp -r -L /root/parts/oai-gnutls/install/usr/local/bin/* /usr/bin/
      cp -r -L /root/parts/oai-gnutls/install/usr/local/share/* /usr/share/
      
      cp -r -L /root/parts/oai-nettle/install/usr/local/include/* /usr/include/
      cp -r -L /root/parts/oai-nettle/install/usr/local/lib/* /usr/lib/
      cp -r -L /root/parts/oai-nettle/install/usr/local/bin/* /usr/bin/
      cp -r -L /root/parts/oai-nettle/install/usr/local/share/* /usr/share/
      
      cp -r -L /root/parts/oai-asn1c/install/usr/local/bin/* /usr/local/bin/
      cp -r -L /root/parts/oai-asn1c/install/usr/local/share/* /usr/local/share/
      
      cp -r -L /root/parts/oai-freediameter/install/usr/local/include/* /usr/local/include/
      cp -r -L /root/parts/oai-freediameter/install/usr/local/lib/* /usr/local/lib/
      cp -r -L /root/parts/oai-freediameter/install/usr/local/bin/* /usr/local/bin/
      
      bazel build lte/gateway/release:release_build --config=production
      cp -L -r bazel-bin/lte/gateway/release/* $SNAPCRAFT_PART_INSTALL/
