name: magma-access-gateway
base: core20
version: '1.8'
summary: Magma's core network
description: Magma's core network

grade: devel
confinement: devmode

package-repositories:
  - type: apt
    components:
      - main
    suites:
      - focal-1.7.0
      - focal-ci
    formats: [deb]
    url: https://linuxfoundation.jfrog.io/artifactory/magma-packages-test
    key-id: FB072E500E692F4E33379EE506E3BFB19BA418A8
    key-server: https://linuxfoundation.jfrog.io/artifactory/api/security/keypair/magmaci/public
  - type: apt
    components:
      - jdk1.8
    suites:
      - stable
    url: https://storage.googleapis.com/bazel-apt
    key-id: 71A1D0EFCFEB6281FD0437C93D5919B448457EE0
    key-server: https://bazel.build/bazel-release.pub.gpg

parts:

  fmt:
    plugin: cmake
    source: https://github.com/fmtlib/fmt.git
    source-type: git
    source-tag: 9.1.0
    cmake-parameters:
      - -DBUILD_SHARED_LIBS=ON
      - -DFMT_TEST=0

  folly:
    plugin: cmake
    after:
      - fmt
    source: https://github.com/facebook/folly
    source-type: git
    source-tag: v2021.02.15.00
    cmake-parameters:
      - -DBUILD_SHARED_LIBS=on
    build-packages:
      - libgoogle-glog-dev
      - libgflags-dev
      - libboost-all-dev
      - libevent-dev
      - libdouble-conversion-dev
      - libboost-chrono-dev
      - libiberty-dev
      - libssl-dev
    override-build: |
      set -x
      cp -r /root/parts/fmt/install/usr/local/include/* /usr/local/include/
      cp -r /root/parts/fmt/install/usr/local/lib/* /usr/local/lib/
      snapcraftctl build

  magma-access-gateway:
    plugin: nil
    after:
      - folly
    source: https://github.com/magma/magma
    source-type: git
    build-packages:
      - apt-transport-https
      - apt-utils
      - bazel=5.2.0
      - bcc-tools
      - bison
      - build-essential
      - ca-certificates
      - cmake
      - curl
      - gcc
      - gnupg2
      - g++
      - iproute2
      - iputils-ping
      - flex
      - libconfig-dev
      - libcurl4-openssl-dev
      - libczmq-dev
      - libgcrypt-dev
      - libgmp3-dev
      - libidn11-dev
      - liblfds710
      - libmnl-dev=1.0.4-2
      - libpcap-dev=1.9.1-3
      - libsctp1
      - libsqlite3-dev
      - libsctp-dev
      - libssl-dev
      - libsystemd-dev
      - lld
      - net-tools
      - oai-asn1c
      - oai-freediameter
      - oai-gnutls
      - oai-nettle
      - netbase
      - python3.8
      - python-is-python3
      - python3-distutils
      - systemd
      - uuid-dev
      - vim
      - libtool=2.4.6-14
    override-build: |
      set -x
      cp -r /root/parts/folly/install/usr/local/include/* /usr/local/include/
      cp -r /root/parts/folly/install/usr/local/lib/* /usr/local/lib/
      mkdir -p /workspaces/magma /etc/magma/
      cp -r . /workspaces/magma/
      cp -r lte/gateway/configs /etc/magma/
      ln -f -s /workspaces/magma/.bazel-cache /var/cache/bazel-cache
      ln -f -s /workspaces/magma/.bazel-cache-repo /var/cache/bazel-cache-repo

      bazel build lte/gateway/release:sctpd_deb_pkg --config=production

      ls -lrta /workspaces/magma/lte/gateway/
      ls -lrta /workspaces/magma/lte/gateway/release/
      cp -r /workspaces/magma/lte/gateway/release/